// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTtVF2e2UrDZEgahZHVjxDmTmT1Yv25JY',
    appId: '1:793401062162:web:385497110e8dbc52a939cb',
    messagingSenderId: '793401062162',
    projectId: 'smart-entry-app',
    authDomain: 'smart-entry-app.firebaseapp.com',
    storageBucket: 'smart-entry-app.firebasestorage.app',
    measurementId: 'G-QE6JNEPJ8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1E6ut3f6qz866CpgOCUUDvmiSSGbn2Qk',
    appId: '1:793401062162:android:1a70d94dc670d9fda939cb',
    messagingSenderId: '793401062162',
    projectId: 'smart-entry-app',
    storageBucket: 'smart-entry-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTtVF2e2UrDZEgahZHVjxDmTmT1Yv25JY',
    appId: '1:793401062162:web:ab29ec3b92eb0857a939cb',
    messagingSenderId: '793401062162',
    projectId: 'smart-entry-app',
    authDomain: 'smart-entry-app.firebaseapp.com',
    storageBucket: 'smart-entry-app.firebasestorage.app',
    measurementId: 'G-7BCMRJ78JL',
  );

}